### ISSUE TITLE
plugin shows dialog on start, even on full Cudatext

### ISSUE THREAD

**Issue by Alexey-T** [Artem3213212/cuda_multi_installer#3]
on Linux

**Comment by Alexey-T** [comment]
after closing dialog by Skip, error
```
Python 3.6.5
Read channels:
  getting: plugins.json
  getting: linters.json
  getting: data.json
  getting: snippets.json
  getting: lexers.json
  getting: kv-addons.json
Startup: total: 108240ms, including plugins: 107480ms
TypeError: an integer is required (got type NoneType)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_multi_installer/__init__.py", line 319, in on_start
    self.open_menu()
  File "/home/user/.cudatext/py/cuda_multi_installer/__init__.py", line 292, in open_menu
    self.show_progerss()
  File "/home/user/.cudatext/py/cuda_multi_installer/__init__.py", line 184, in show_progerss
    'w': 50})
  File "/home/user/.cudatext/py/cudatext.py", line 942, in dlg_proc
    res = ct.dlg_proc(id_dialog, id_action, to_str(prop), index, index2, name)
SystemError: <built-in function dlg_proc> returned a result with an error set
```
